// This file has been autogenerated. The following properties could not be retrieved from the API or would not make sense in a different org e.g. Edge IDs
// The variables contained in this file have been given default values and should be edited as necessary

genesyscloud_integration_credential_Integration-3f6d90e6-18aa-4956-b952-56ce28b96be4_fields = null